project:
  type: website
  output-dir: _site
  
  preview: 
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
  
  render:
    - "*.qmd"
    - "*.md"
  
  resources:
    - Burcham_CV.pdf

# Metadata stuff
pagetitle: "{{< meta title >}} | {{< meta website.title >}}"
description-meta: "{{< meta description >}}"
author-meta: "Daniel Burcham"

website:
  title: "Daniel Burcham"
  description: "Daniel Burcham is an assistant professor at Colorado State University studying and teaching about trees"
  site-url: "http://danielburcham.dev"
  repo-url: "https://github.com/danielburcham/dcb-quarto-site"
  
  google-analytics: "G-Y33GXW5WS7"
  cookie-consent: true
  
  open-graph:
    locale: en_US

  comments:
    utterances:
      repo: Documents/danielburcham.dev

  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        href: "research/index.qmd"
      - text: "Blog"
        href: "blog/index.qmd"
  page-footer:
    left: "© Copyright 2022 Daniel Burcham"
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
  
format:
  html:
    code-link: true
    css: styles.css
    theme: [sandstone, _variables.scss]
    embed-resources: true