---
title: "Effect of pruning type and severity on vibration properties and mass of Senegal mahogany (*Khaya senegalensis*) and rain tree (*Samanea saman*)"
date: 2019-09-26
author:
  - name: Daniel C. Burcham
    url: https://danielburcham.dev
    orcid: 0000-0002-1793-3945
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Wesley R. Autio
    url: https://stockbridge.cns.umass.edu/wesley-autio
    orcid: 0000-0002-2938-7101
    affiliation: Stockbridge School of Agriculture, University of Massachusetts Amherst
  - name: Kenneth James
    affiliation: Melbourne School of Land and Environment, University of Melbourne
  - name: Yahya Modarres-Sadeghi
    url: https://mie.umass.edu/faculty/yahya-modarres-sadeghi
    affiliation: Department of Mechanical and Industrial Engineering, University of Massachusetts Amherst
  - name: Brian Kane
    url: https://eco.umass.edu/people/faculty/kane-brian-c-p/
    orcid: 0000-0002-2814-0801
    affiliation: Department of Environmental Conservation, University of Massachusetts Amherst
categories:
  - Biomechanics
  - Vibration properties
  - Pruning
pub-info:
  reference: >-
    <strong>Daniel C. Burcham</strong>, <a href="https://stockbridge.cns.umass.edu/wesley-autio">Wesley R. Autio</a>, Kenneth James, <a href="https://mie.umass.edu/faculty/yahya-modarres-sadeghi">Yahya Modarres-Sadeghi</a>, and <a href="https://eco.umass.edu/people/faculty/kane-brian-c-p/">Brian Kane</a>. 2020. Effect of pruning type and severity on vibration properties and mass of Senegal mahogany (<em>Khaya senegalensis</em>) and rain tree (<em>Samanea saman</em>). Trees: Structure and Function 34: 213-228. doi: <a href="https://doi.org/10.1007/s00468-019-01912-8"><code>10.1007/s00468-019-01912-8</code></a>
  links:
    - name: Preprint
      url: TSAF-D-19-00177.pdf
      icon: fa-solid fa-file-pdf
      local: TRUE
    - name: Final version
      url: https://doi.org/10.1007/s00468-019-01912-8
      icon: fa-solid fa-scroll
doi: 10.1007/s00468-019-01912-8
---

## Abstract

During pruning, arborists often intend to increase a tree’s resistance to wind loading by selectively removing branches, but there are few studies examining the efficacy of these interventions, especially for large, open-grown trees. This study examined the vibration properties (frequency and damping ratio) and mass of Senegal mahogany (*Khaya senegalensis*) and rain tree (*Samanea saman*) before and after a series of pruning treatments: crowns were either raised or reduced at incremental severities between 0 and 80%. For both species, mass decreased faster on reduced than raised trees. The frequency and damping ratio of trees varied with the severity of pruning for reduced, but not raised, trees. The frequency of reduced trees generally increased with pruning severity. In contrast, damping ratio of reduced trees generally decreased with the severity of pruning, except for the unique increase in damping ratio on Senegal mahoganies reduced by 10–20%. Although the vibration properties and mass will change as trees grow after pruning, the results suggest that arborists can reduce trees to change their vibration properties and concomitant response to wind loads, but arborists should reduce trees by a small amount to avoid the adverse decrease in damping ratio.

## Illustrative figure

![Figure 4: Pre-treatment time history of trunk displacement measured during free vibration on Senegal mahogany (*Khaya senegalensis*) tree number 16 (KS16), including the equation of motion for a damped harmonic oscillator (solid blue line) fit to recorded observations (bottom); and power spectral density plot with annotation showing peak frequency (top).](Tree_16_Dose_0_D1_Pluck_Test_R2_Truncated_Irregular_Intervals.png)

## Materials

-   [Paper (preprint)](TSAF-D-19-00177.pdf))

## BibTeX citation

``` bibtex
@article{BurchamAutioJamesModarresSadeghiKane:2020,
    Author = {Daniel C. Burcham, Wesley R. Autio, Kenneth James, Yahya Modarres-Sadeghi, and Brian Kane},
    Doi = {10.1007/s00468-019-01912-8},
    Journal = {Trees: Structure and Function},
    Month = {9},
    Pages = {213-228},
    Title = {Effect of pruning type and severity on vibration properties and mass of Senegal mahogany (Khaya senegalensis) and rain tree (Samanea saman)},
    Volume = {34},
    Year = {2020}}
```
