---
title: "Can sonic tomography predict loss in load-bearing capacity for trees with internal defects? A comparison of sonic tomograms with destructive measurements"
date: 2019-01-05
author:
  - name: Daniel C. Burcham
    url: https://danielburcham.dev
    orcid: 0000-0002-1793-3945
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Nicholas J. Brazee
    url: https://ag.umass.edu/people/nicholas-j-brazee-phd
    affiliation: Center for Agriculture, Food, and the Environment, University of Massachusetts Amherst
  - name: Robert E. Marra
    url: https://portal.ct.gov/CAES/ABOUT-CAES/Staff-Biographies/Robert-E-Marra
    affiliation: Connecticut Agricultural Experiment Station
  - name: Brian Kane
    url: https://eco.umass.edu/people/faculty/kane-brian-c-p/
    orcid: 0000-0002-2814-0801
    affiliation: Department of Environmental Conservation, University of Massachusetts Amherst
categories:
  - Biomechanics
  - Decay
  - Risk assessment
  - Sonic tomography
pub-info:
  reference: >-
    <strong>Daniel C. Burcham</strong>, <a href="https://ag.umass.edu/people/nicholas-j-brazee-phd">Nicholas J. Brazee</a>, <a href="https://portal.ct.gov/CAES/ABOUT-CAES/Staff-Biographies/Robert-E-Marra">Robert E. Marra</a>, <a href="https://eco.umass.edu/people/faculty/kane-brian-c-p/">Brian Kane</a>. Can sonic tomography predict loss in load-bearing capacity for trees with internal defects? A comparison of sonic tomograms with destructive measurements. Trees: Structure and Function 33(3):681-695. doi: <a href="https://doi.org/10.1007/s00468-018-01808-z"><code>10.1007/s00468-018-01808</code></a>
  links:
    - name: Preprint
      url: TSAF-D-18-00180.pdf
      icon: fa-solid fa-file-pdf
      local: TRUE
    - name: Final version
      url: https://doi.org/10.1007/s00468-018-01808-z
      icon: fa-solid fa-scroll
    - name: Software package
      url: https://github.com/danielburcham/zloss
      icon: fa-brands fa-github
doi: 10.1007/s00468-018-01808-z
---

## Abstract

The measurement and assessment of internal defects is an important aspect of tree risk assessment. Although there are several methods for estimating the reduced load-bearing capacity of trees with internal defects, the advancement of these methods has not kept pace with improvements to methods used to measure the internal condition of trees, such as sonic tomography. In this study, the percent reduction to the section modulus, *Z*~LOSS~ (%), caused by internal defects was estimated using 51 sonic tomograms collected from three tree species, and the accuracy of measurements was assessed using the destructively measured internal condition of the corresponding cross sections. In tomograms, there was a repeated underestimation of the percent total damaged area, *A*~D~(%), and a repeated overestimation of the offset distance between the centroid of the trunk and the centroid of the largest damaged part, *L*~O~ (m). As a result, *Z*~LOSS~ determined using tomograms was mostly less, in absolute terms, than that determined from destructive measurements. However, the accuracy of these estimates improved when using colors associated with intermediate sonic velocities to select damaged parts in tomograms, in addition to the colors explicitly associated with the slowest sonic velocities. Among seven mathematical methods used to estimate *Z*~LOSS~, those accounting for *L*~O~ were more accurate than others neglecting it. In particular, a numerical method incorporating greater geometric detail, called `zloss`, gave estimates that were consistently better than six other analytical methods.

## Illustrative figure
![Figure 1: Based on measurements of acoustic transmission speeds, a PiCUS sonic tomogram depicts the internal condition of trees using a four category colorimetric scale: brown depicts regions with the highest acoustic transmission speeds associated with undamaged wood; green depicts regions with intermediate acoustic speeds; violet and blue depict regions with progressively slower acoustic transmission speeds associated with damaged wood.](AB07_050.jpg){width=60%}

![Figure 2: The `zloss` function estimates the reduced load-bearing capacity of tree parts with internal damage by computing the percent decrease to the section modulus, *Z*~LOSS~ (%), equivalent to the percent increase in local stress caused by the loss of supporting wood. The estimates can be used by arborists evaluating the severity of internal damage during advanced tree risk assessment. In the example depicted, the tree part was nearly 29% decayed, but its load-bearing capacity was only reduced by 13%.](AB07_050_ZLoss.png)

## Materials

-   [Paper (preprint)](TSAF-D-18-00180.pdf)
-   [Software package](https://github.com/danielburcham/zloss)

## BibTeX citation

``` bibtex
@article{BurchamBrazeeMarraKane:2019,
    Author = {Daniel C. Burcham, Nicholas J. Brazee, Robert E. Marra, Brian Kane},
    Doi = {10.1007/s00468-018-01808-z},
    Journal = {Trees: Structure and Function},
    Month = {1},
    Pages = {681-695},
    Title = {Can sonic tomography predict loss in load-bearing capacity for trees with internal defects? A comparison of sonic tomograms with destructive measurements},
    Volume = {33},
    Year = {2019}}
```