---
title: "Identifying modal properties of trees with Bayesian inference"
date: 2022-04-01
author:
  - name: Daniel C. Burcham
    url: https://danielburcham.dev
    orcid: 0000-0002-1793-3945
    affiliation: Department of Horticulture and Landscape Architecture, Colorado State University
  - name: Siu-Kui Au
    url: https://dr.ntu.edu.sg/cris/rp/rp00182
    orcid: 0000-0002-0228-1796
    affiliation: School of Civil and Environmental Engineering, Nanyang Technological University
categories:
  - Biomechanics
  - Vibration properties
pub-info:
  reference: >-
    <strong>Daniel C. Burcham</strong> and <a href="https://dr.ntu.edu.sg/cris/rp/rp00182">Siu-Kui Au</a>. 2022. Identifying modal properties of trees with Bayesian inference. Agricultural and Forest Meteorology  316: 108804. doi: <a href="https://doi.org/10.1016/j.agrformet.2021.108804"><code>10.1016/j.agformet.2021.108804</code></a>
  links:
    - name: Preprint
      url: AGFORMET-D-20-01560.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1016/j.agrformet.2021.108804
      icon: fa-solid fa-scroll
    - name: Data
      url: https://doi.org/10.7910/DVN/FHJBYG
      icon: fa-solid fa-table
doi: 10.1016/j.agrformet.2021.108804
---

## Abstract

In forested landscapes, the presence of trees enhances turbulent airflow governing the exchange of momentum, heat, and gas between the atmosphere and biosphere, especially when horizontal motion dominates near-surface winds, and tree vibration is a prominent feature of the dynamic interaction between wind and trees. The vibration characteristics of trees reflect their underlying mechanical properties (i.e., mass, stiffness, damping) and govern their response to dynamic loads. Despite numerous investigations of tree vibration, there have been few studies examining methodological improvements for identifying and characterizing variability in the modal properties of trees during ambient wind excitation. In the engineering disciplines, however, there are several techniques commonly used to estimate the modal properties of a structure from its ambient vibration, often called 'operational modal analysis' (OMA). Operating in the frequency domain, this study examined the use of Bayesian OMA for identifying several important modal properties, including frequencies, damping ratios, and partial mode shapes, as well as their identification uncertainty. Using the ambient vibration recorded on a mature *Hopea odorata* Roxb. (Dipterocarpaceae) tree over a one-week period, the identified modal properties and associated uncertainties were physically reasonable and consistent with previous measurements for trees, and the identification uncertainty was much greater for damping ratio than frequency, which can be explained theoretically. Beyond the consistency with existing measurements, the analysis also yielded new insight about the vibration behavior of large trees. The modal properties varied considerably over consecutive one-hour intervals, and the changes were likely related to differences in wind excitation during each period, suggesting the existence of amplitude dependence in the modal properties of trees. Over the same periods, there were consistently two close modes (i.e., with similar frequencies), oriented approximately orthogonal to one another, near the tree's fundamental frequency. With additional evaluation and refinement, the techniques can be used for OMA of trees in different settings.

## Illustrative figure

![Figure 5: Tracking changes in modal properties (frequency, damping ratio, and modal force PSD) identified from the ambient vibration of a mature *Hopea odorata* Roxb. (Dipterocarpaceae) tree over one week. Individial observations show the estimates for a one-hour time window, with a marker at the most probable value (MPV) and two-standard deviation error bar indicating identification uncertainty. The green and blue markers denote estimates for mode 1 and mode 2, respectively.](Figure_5_evo_idresult_track.png)

## Materials

-   [Paper (preprint)](AGFORMET-D-20-01560.pdf)
-   [Data](https://doi.org/10.7910/DVN/FHJBYG)

## BibTeX citation

``` bibtex
@article{BurchamAu:2022,
    Author = {Daniel C. Burcham and Siu-Kui Au},
    Doi = {10.1016/j.agrformet.2021.108804},
    Journal = {Agricultural and Forest Meteorology},
    Month = {4},
    Pages = {108804},
    Title = {Identifying modal properties of trees with Bayesian inference},
    Volume = {316},
    Year = {2022}}
```
