---
title: "Geometry matters for sonic tomography of trees"
date: 2023-01-18
author:
  - name: Daniel C. Burcham
    url: https://danielburcham.dev
    orcid: 0000-0002-1793-3945
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Nicholas J. Brazee
    url: https://ag.umass.edu/people/nicholas-j-brazee-phd
    orcid: 0000-0003-3124-4684
    affiliation: Center for Agriculture, Food, and the Environment, University of Massachusetts Amherst
  - name: Robert E. Marra
    url: https://portal.ct.gov/CAES/ABOUT-CAES/Staff-Biographies/Robert-E-Marra
    affiliation: Connecticut Agricultural Experiment Station
  - name: Brian Kane
    url: https://eco.umass.edu/people/faculty/kane-brian-c-p/
    orcid: 0000-0002-2814-0801
    affiliation: Department of Environmental Conservation, University of Massachusetts Amherst
categories:
  - Decay
  - Risk assessment
  - Sonic tomography
pub-info:
  reference: >-
    <strong>Daniel C. Burcham</strong>, <a href="https://ag.umass.edu/people/nicholas-j-brazee-phd">Nicholas J. Brazee</a>, <a href="https://portal.ct.gov/CAES/ABOUT-CAES/Staff-Biographies/Robert-E-Marra">Robert E. Marra</a>, <a href="https://eco.umass.edu/people/faculty/kane-brian-c-p/">Brian Kane</a>. 2023. Geometry matters for sonic tomography of trees. Trees: Structure and Function 37(3):837-848. doi: <a href="https://doi.org/10.1007/s00468-023-02387-4"><code>10.1007/s00468-023-02387-4</code></a>
  links:
    - name: Preprint
      url: TSAF-D-22-00307.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1007/s00468-023-02387-4
      icon: fa-solid fa-scroll
    - name: Code
      url: https://github.com/danielburcham/geomProp
      icon: fa-brands fa-github
    - name: Data
      url: https://doi.org/10.7910/DVN/RGJFMR
      icon: fa-solid fa-table
doi: 10.1007/s00468-023-02387-4
---

## Abstract

For trees growing in communities, arborists routinely check for evidence of damaged wood during tree risk assessment, and sonic tomography is occasionally used to measure the amount of internal damage in trees. Existing studies investigating the accuracy of commercially available sonic tomography devices have mostly considered a limited range of measurement conditions, limiting their application in practice. Using measurements incorporating greater variability in test conditions, this study examined the accuracy of sonic tomography by comparing the percent damaged cross-sectional area in tomograms with the destructively measured internal condition of trees. Although the accuracy of tomograms differed between the examined temperate and tropical tree species, the variation was largely explained by underlying differences in the cross-sectional geometry of the measured tree parts. The amount of decay was repeatedly underestimated in measurements of small, circular cross sections, and, conversely, it was consistently overestimated in measurements of large, irregularly shaped cross sections. Using different approaches to generating and interpreting tomograms, a wide range of decay estimates was obtained for a given set of measurements. By adjusting software settings, it was possible to obtain tomograms with the least error for a given cross-sectional geometry, and the tomograms could be visually interpreted to similarly compensate for the anticipated measurement error. Although practitioners can use the identified strategies to compensate for the expected measurement error in different situations, there is also a fundamental need to develop improved measurement and analysis routines for sonic tomography relying on physically realistic assumptions about acoustic wave propagation in wood.

## Illustrative figure

![Figure 1: Using the PiCUS Sonic Tomograph 3, the accuracy of sonic tomography was examined by comparing tomograms (left) with the destructively measured internal condition (center) of trees with different cross-sectional geometries, including large, irregularly shaped (**A**), large, round (**B**), and small, circular trees (**C**). For reference, the length of the white scale bar is 10 cm, and the default calculation method (SoT 1) was used to create the displayed tomograms. The reference photographs were manually converted into binary images (right), in which black (0) and white (1) represented the absence or presence, respectively, of solid wood. The extent of damaged wood depicted by specific colors in each tomogram was compared with the corresponding binary image. Using the default software settings, the amount of damage depicted in tomograms was noticeably greater (**A**) and less (**C**) than the actual extent of damaged wood in the large, concave (*A* = 1.58 m^2^, *S* = 0.72) angsana (*Pterocarpus indicus*) and small, circular (*A* = 0.16 m^2^, *S* = 0.99) American beech (*Fagus grandifolia*), respectively. In contrast, the amount of damage was more reasonably depicted (**B**) in the large, convex santol (*Sandoricum koetjape*) section (*A* = 1.18 m^2^, *S* = 0.95).](Figure_1.jpg){width="90%"}

## Materials

-   [Paper (preprint)](TSAF-D-22-00307.pdf)
-   [Code](https://github.com/danielburcham/geomProp)
-   [Data](https://doi.org/10.7910/DVN/RGJFMR)

## BibTeX citation

``` bibtex
@article{BurchamBrazeeMarraKane:2019,
    Author = {Daniel C. Burcham, Nicholas J. Brazee, Robert E. Marra, Brian Kane},
    Doi = {10.1007/s00468-023-02387-4},
    Journal = {Trees: Structure and Function},
    Month = {1},
    Pages = {837-848},
    Title = {Geometry matters for sonic tomography of trees},
    Volume = {37},
    Issue = {3},
    Year = {2023}}
```
