---
title: "Characterization of host-fungus interactions among wood decay fungi associated with *Khaya senegalensis* (Desr.) A. Juss (Meliaceae) in Singapore"
date: 2015-05-30
author:
  - name: Daniel C. Burcham
    url: https://danielburcham.dev
    orcid: 0000-0002-1793-3945
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Jia-Yih Wong
    affiliation: Plant Health Laboratory Department, Agri-Food & Veterinary Authority, Singapore
  - name: Mohamed Ismail Mohamed Ali
    affiliation: Plant Health Laboratory Department, Agri-Food & Veterinary Authority, Singapore
  - name: Nelson V. Abarrientos
    orcid: 0000-0003-2046-2723
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Yok-King Fong
    affiliation: Centre for Urban Greenery and Ecology, National Parks Board, Singapore
  - name: Francis W.M.R. Schwarze
    affiliation: Applied Wood Materials, Empa Swiss Federal Laboratories for Science and Technology, St. Gallen, Switzerland
    orcid: 0000-0003-3306-8303
categories:
  - Wood decay
  - Host-fungus interaction
pub-info:
  reference: >-
    <strong>Daniel C. Burcham</strong>, Jia-Yih Wong, Mohamed Ismail Mohamed Ali, Nelson V. Abarrientos, Yok-King Fong, and Francis W.M.R. Schwarze. 2015. Characterization of host-fungus interactions among wood decay fungi associated with <em>Khaya senegalensis</em> (Desr.) A. Juss (Meliaceae) in Singapore. Forest Pathology 45: 492-504. doi: <a href="https://doi.org/10.1111/efp.12199"><code>10.1111/efp.12199</code></a>
  links:
    - name: Preprint
      url: EFP_12199.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1111/efp.12199
      icon: fa-solid fa-scroll
doi: 10.1111/efp.12199
---

## Abstract

Tree pruning creates wounds that are amenable for wood decay fungi colonization. To characterize the dynamic host–fungus interactions at this location in Senegal mahogany (*Khaya senegalensis*), in vitro and in vivo pathogenicity tests were conducted with wood decay fungi associated with this tropical tree species. *Fomitiporella caryophylii*, *Hymenochaete murina* and *Phellinus noxius* isolates were included in this experiment following their frequent isolation from Senegal mahogany pruning wounds. The evaluated isolates demonstrated unique host interactions in laboratory tests that suggest equally divergent prognoses for living Senegal mahoganies affected by these fungi. Although all evaluated fungal isolates successfully breached naturally induced reaction zones, *P. noxius* alone caused significant mass loss to incubated wood blocks. In addition, *P. noxius* caused extensive wood decay after inoculation in living hosts, successfully illustrating Koch’s postulates for this host–fungus relationship. The wood decay ability, invasiveness and facultative parasitism demonstrated by *P. noxius* suggest its dominant role in wood decay columns below pruning wounds on living Senegal mahoganies. These results highlight the importance of characterizing specific host–fungus interactions and their implications for wood decay severity below pruning wounds in living trees.

## Illustrative figure

![Figure 3: **(a)** A transverse section (TS) showing the typical anatomical features of Senegal mahogany sapwood, including vessesl (V), axial parenchyma (AP), radial parenchyma (RP), and libriform wood fibres (F). Bar, 100 \mum. **(b)** A TS of a Senegal mahogany reaction zone showing extensive, uniform polyphenolic deposits within all cellular constituents (arrows). Note: the absense of fungal hyphae and cell wall decomposition from the uninoculated (control) reaction zone wood confirms the sole presence of the intended fungal isolate in the treatment groups.](Fig_3.jpg)

## Materials

-   [Paper (preprint)](EFP_12199.pdf)

## BibTeX citation

``` bibtex
@article{Burchametal:2017,
    Author = {Daniel C. Burcham, Jia-Yih Wong, Mohamed Ismail Mohamed Ali, Nelson V. Abarrientos, .Yok-King Fong, Francis W.M.R. Schwarze},
    Doi = {10.1111/efp.12199},
    Journal = {Forest Pathology},
    Month = {5},
    Pages = {492-504},
    Title = {Characterization of host-fungus interactions among wood decay fungi associated with Khaya senegalensis (Desr.) A. Juss (Meliaceae) in Singapore},
    Volume = {45},
    Year = {2015}}
```
