name: Build and deploy dcb-quarto-site
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        
      - name: "Setup pandoc"
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            cran::shinylive@0.1.1 ## Pin version to ensure consistency
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            
      - name: "Setup Renv"
        uses: r-lib/actions/setup-renv@v2
      
      - name: "Setup Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Create .ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      
      - name: Install SSH key
        run: echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519_deploy && chmod 600 ~/.ssh/id_ed25519_deploy
      
      - name: Create known hosts
        run: echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Deploy site
        run: rsync -a -e "ssh -i ~/.ssh/id_ed25519_deploy" _site deploy@146.190.32.124:/home/deploy/dcb-quarto-site
