name: Build and deploy dcb-quarto-site
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      - name: Create SSH key and known hosts
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          ssh_host: 146.190.32.124
      - uses: quarto-dev/quarto-actions/render@v2
      - name: Render site
        run: | 
          quarto render
          echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
      - name: Deploy site
        run: rsync -a ${{ env.QUARTO_OUTPUT }} dan@146.190.32.124:/home/dan/dcb-quarto-site/site