name: Build and deploy dcb-quarto-site
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - name: Create .ssh directory
        run: mkdir ~/.ssh && chmod 600 ~/.ssh
      - name: Install SSH key
        run: echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519_deploy
      - name: Create known hosts
        run: echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy site
        run: rsync -a -e "ssh -i ~/.ssh/id_ed25519_deploy" ${{ env.QUARTO_OUTPUT }} deploy@146.190.32.124:/home/deploy/dcb-quarto-site